homeassistant:
  customize:
    input_boolean.notify_camera_alerts:
      name: Уведомления с камеры

telegram_bot:
  - platform: polling
    api_key: !secret api_key
    parse_mode: html
    allowed_chat_ids:
      - !secret chat_id

notify:
  - name: telegram
    platform: telegram
    chat_id: !secret chat_id

input_boolean:
  notify_camera_alerts:
      initial: on
      icon: mdi:calendar-check

automation:
#Уведомление в телеграмм о движении если Денис не Дома
  - alias: Notify Camera Snapshots
    initial_state: true
    trigger:
## Открытие входной двери
      platform: state
      entity_id: binary_sensor.door_window_sensor_158d00020f8533
      from: 'off'
      to: 'on'
    condition:
      - condition: template
        value_template: "{{ states('input_boolean.notify_camera_alerts') == 'on' }}"
    action:
      - delay: "{{ '00:00:08' if states.binary_sensor.door_window_sensor_158d00020f8533.state == 'on' else '0:0:0' }}"
      - service: notify.telegram
        data_template:
          message: >
            Открыта входная дверь
      - service: notify.telegram
        data_template:
          message: Message
          data: 
            photo:
              url: 'http://127.0.0.1:8123{{states.camera.dafang.attributes.entity_picture}}'
              caption: '{{now().strftime("%d.%m.%Y-%H:%M:%S")}}'

## Звонок в дверь 
  - alias: 01_frontdoor_switch_on
    initial_state: true
    trigger:       
     platform: state
     entity_id: binary_sensor.switch_158d00023e4abc
     to: 'on'
    action:
    - service: notify.telegram
      data:
        title: "Входная дверь"
        message: "Звонок в дверь {{ states('sensor.time_date') }}"

## Обнаружение протечки, душевая кабина  
  - alias: 06_bathroom_wleak_shower_on
    initial_state: true
    trigger:       
     platform: state
     entity_id: binary_sensor.water_leak_sensor_158d000256d281
     to: 'on'
    action:
    - service: notify.telegram
      data:
        title: "Обнаружена протечка"
        message: "Санузел душевая {{ states('sensor.time_date') }}"

## Протечка устранена, душевая кабина    
  - alias: 06_bathroom_wleak_shower_off
    initial_state: true
    trigger:       
     platform: state
     entity_id: binary_sensor.water_leak_sensor_158d000256d281
     from: 'on'
     to: 'off'
    action:
    - service: notify.telegram
      data:
        title: "Протечка устранена"
        message: "Санузел душевая {{ states('sensor.time_date') }}"

## Обнаружение протечки, раковина     
  - alias: 04_kitchen_wleak_washstand_on
    initial_state: true
    trigger:       
     platform: state
     entity_id: binary_sensor.water_leak_sensor_158d00022f008f
     to: 'on'
    action:
    - service: notify.telegram
      data:
        title: "Обнаружена протечка"
        message: "Кухня раковина {{ states('sensor.time_date') }}"

## Протечка устранена, раковина          
  - alias: 04_kitchen_wleak_washstand_off
    initial_state: true
    trigger:       
     platform: state
     entity_id: binary_sensor.water_leak_sensor_158d00022f008f
     from: 'on'
     to: 'off'
    action:
    - service: notify.telegram
      data:
        title: "Протечка устранена"
        message: "Кухня раковина {{ states('sensor.time_date') }}"

## Дым обнаружен 
  - alias: 04_kitchen_smoke_on
    initial_state: true
    trigger:       
     platform: state
     entity_id: binary_sensor.smoke_sensor_158d00045e9238
     to: 'on'
    action:
    - service: notify.telegram
      data:
        title: "Сработал датчик дыма"
        message: "Кухня {{ states('sensor.time_date') }}"

## Дым устранен         
  - alias: 04_kitchen_smoke_off
    initial_state: true
    trigger:       
     platform: state
     entity_id: binary_sensor.smoke_sensor_158d00045e9238
     from: 'on'
     to: 'off'
    action:
    - service: notify.telegram
      data:
        title: "Датчик дыма отключен"
        message: "Кухня {{ states('sensor.time_date') }}"