asuswrt:
  host: 192.168.1.1
  username: !secret asus_username
  password: !secret asus_password

life360:
  accounts:
    - username: !secret life360_username
      password: !secret life360_password

device_tracker:
- platform: asuswrt
  host: 192.168.1.1
  username: !secret asus_username
  password: !secret asus_password
  track_new_devices: yes

- platform: life360
  username: !secret life360_username
  password: !secret life360_password
  max_gps_accuracy: 200
  show_as_state: places

sensor:
  - platform: template
    sensors:
      life360_wifi_status:
        friendly_name: 'Phone WiFi Status'
        icon_template: >
          mdi:wifi
          {{- '' if state_attr('device_tracker.life360_denis', 'wifi_on') else '-off' }}
        value_template: >
          {{ '' if state_attr('device_tracker.life360_denis', 'wifi_on') else 'Not ' -}}
          Connected
      life360_battery_charge_status:
        friendly_name: 'Phone Battery Status'
        icon_template: mdi:battery-charging-wireless-alert
        value_template: >
          {{ 'Charging' if state_attr('device_tracker.life360_denis', 'battery_charging')
             else 'Unplugged' }}
      life360_battery_level_status:
        friendly_name: "Phone Battery"
        unit_of_measurement: "%"
        value_template: "{{ state_attr('device_tracker.life360_denis', 'battery') }}"
