media_player:
  - platform: dlna_dmr
    url: http://192.168.1.13:2870/dmr.xml
    name: soundbar

transmission:
  host: 192.168.1.40

cast:
  media_player:
    - host: 192.168.1.11
      name: GHM1
    - host: 192.168.1.12
      name: GHM2
    - host: 192.168.1.15
      name: chromecast

# sensor:
#   - platform: plex_recently_added
#     name: Recently Added Movies # will create sensor.recently_added_movies
#     host: !secret plex_host
#     token: !secret plex_token
#     port: 32400
#     section_types:
#     - movie

#   - platform: plex_recently_added
#     name: Recently Added TV  # will create sensor.recently_added_tv
#     host: !secret plex_host
#     token: !secret plex_token
#     port: 32400
#     section_types:
#     - show

automation:
- alias: Completed Torrent
  trigger:
    platform: event
    event_type: transmission_downloaded_torrent
  action:
    service: notify.telegram
    data_template:
      title: "Скачивание завершено"
      message: "{{trigger.event.data.name}}"  