hacs:
  token: !secret hacs_token
recorder:
  db_url: mysql://pi:raspberry@core-mariadb/homeassistant?charset=utf8
  purge_keep_days: 2
logger:
  default: error
mqtt:
  broker: 192.168.1.5
  discovery: true
  discovery_prefix: homeassistant
  username: pi
  password: raspberry
homekit:
  auto_start: False
  filter:
    include_domains:
      # - alarm_control_panel
      - climate
      - light
      - switch
google_assistant:
  project_id: !secret google_project_id
  exposed_domains:
    - switch
    - light
    - climate
    - media_player
notify:
  - name: telegram
    platform: telegram
    chat_id: !secret chat_id
binary_sensor:
  - platform: workday
    country: RU

  - platform: tod
    name: tod_night
    after: '22:00'
    before: '06:00'
    
  - platform: tod
    name: tod_morning
    after: '06:00'
    before: '09:00'
    
  - platform: tod
    name: tod_day
    after: '09:00'
    before: '20:00'
    
  - platform: tod
    name: tod_evening
    after: '20:00'
    before: '22:00'
    
  - platform: tod
    name: tod_long_day
    after: '06:00'
    before: '21:30'
    
  - platform: tod
    name: tod_early_night
    after: '21:30'
    before: '06:00'
    
  - platform: tod
    name: tod_full_day
    after: sunrise
    before: sunset
    
  - platform: tod
    name: tod_full_night
    after: sunset
    before: sunrise

sensor:
- platform: systemmonitor
  resources:
  - type: processor_use
  - type: disk_use_percent
    arg: /
  - type: memory_use_percent
  - type: last_boot
  - type: disk_free
    arg: /

- platform: time_date
  display_options:
    - 'time'
    - 'date'
    - 'date_time'
    - 'time_date'

- platform: sql
  db_url: mysql://pi:raspberry@core-mariadb/homeassistant?charset=utf8
  queries:
    - name: Maria DB size
      query: 'SELECT table_schema "database", Round(Sum(data_length + index_length) / 1048576, 2) "value" FROM information_schema.tables WHERE table_schema="homeassistant" GROUP BY table_schema;'
      column: 'value'
      unit_of_measurement: MB
    
- platform: command_line
  name: cpu_temp
  command: "cat /sys/class/thermal/thermal_zone0/temp"
  unit_of_measurement: "°C"
  value_template: '{{ (value | multiply(0.001)) | round(1) }}'

automation:
# HOMEKIT START DELAY
- alias: Start Homekit
  initial_state: 'true'
  trigger:
  - platform: homeassistant
    event: start
  action:
  - delay: 00:03
  - service: homekit.start



