homeassistant:
  customize:
    sun.sun:
      friendly_name: Солнце
    input_boolean.rain_alert:
      hidden: true
    sensor.dark_sky_precip_probability:
      friendly_name: Вероятность осадков
    sensor.dark_sky_precip :
      friendly_name: Осадки
weather:
  - platform: darksky
    api_key: !secret weather_api_key
    mode: daily

input_boolean:
  rain_alert:
    name: Rain Alert
    initial: off

sensor:
  - platform: darksky
    api_key: !secret weather_api_key
    monitored_conditions:
      - summary
      - precip_type
      - precip_intensity
      - precip_probability
      - temperature
      - wind_speed
      - humidity
      - pressure
      - hourly_summary
      - daily_summary
    language: ru

automation:
  - alias: Rain Alerts
    initial_state: true
    trigger:
      platform: state
      entity_id: sensor.dark_sky_precip
    condition:
      - condition: template
        value_template: '{{ trigger.to_state.state | lower == "rain" }}'
      - condition: state
        entity_id: sun.sun
        state: 'above_horizon'
      - condition: template
        value_template: '{% if trigger.to_state.state == "unknown" or trigger.to_state.state == "" %} false {% else %} true {% endif %}'
      - condition: template
        value_template: '{{ states.sensor.dark_sky_precip_probability.state | int == 1 }}'
    action:
      - service: input_boolean.turn_on
        data_template:
          entity_id: >
            {% set curState = trigger.to_state.state | lower %}
            {%- if curState == "rain" -%}
               input_boolean.rain_alert
            {%- endif %}
      - service: notify.telegram
        data_template:
          message: "{{ trigger.to_state.state | title }} с интенсивностью {{ states.sensor.dark_sky_precip_intensity.state | float }} см ч"
