homeassistant:
  customize:
    sun.sun:
      friendly_name: Солнце
    input_boolean.rain_alert:
      hidden: true
    sensor.dark_sky_precip_probability:
      friendly_name: Вероятность осадков
    sensor.dark_sky_precip :
      friendly_name: Осадки
weather:
  - platform: darksky
    api_key: !secret weather_api_key
    mode: daily

input_boolean:
  rain_alert:
    name: Rain Alert
    initial: off

sensor:
  - platform: darksky
    api_key: !secret weather_api_key
    monitored_conditions:
      - summary
      - precip_type
      - precip_intensity
      - precip_probability
      - temperature
      - wind_speed
      - humidity
      - pressure
      - hourly_summary
      - daily_summary
    language: ru