timer:
  washer_b:
    name: Washing duration
    duration: '05:00:00'
    icon: mdi:timer

input_number:
  washer_start:
    name: Washer start
    min: 1567583200
    max: 999999999999999999
    step: 1
    mode: box

binary_sensor:
  - platform: template
    sensors:
      washer_b:
        friendly_name: Washing machine status
        icon_template: mdi:washing-machine
        entity_id: sensor.plug_2_wattage
        delay_off:
          minutes: 2
        value_template: "{{ states.sensor.plug_2_power.state > 10 }}"

sensor:
  - platform: history_stats
    name: Washer ON Monthly
    entity_id: binary_sensor.washer_b
    state: 'on'
    type: time
    start: '{{ now().replace(day=1,hour=0,minute=0,second=0) }}'
    end: '{{ now() }}'
  - platform: history_stats
    name: Washer ON
    entity_id: binary_sensor.washer_b
    state: 'on'
    type: time
    start: '{{ now().replace(hour=0,minute=0,second=0) }}'
    end: '{{ now() }}'

script:
  noop:
    alias: Dummy
    sequence:
      - delay:
          seconds: 0.1 

  washer_timer_on:
    alias: Washer Timer On
    sequence:
      - service: timer.cancel
        entity_id: timer.washer_b
      - service: timer.start
        entity_id: timer.washer_b
      - service: input_number.set_value
        data_template:
          entity_id: input_number.washer_start
          value: '{{as_timestamp (now())|int}}'

  washer_timer_off:
    alias: Washer Timer Off
    sequence:
      - service: timer.cancel
        entity_id: timer.washer_b

automation:
- alias: bathroom_washing_machine
  initial_state: 'true'
  trigger:
    - platform: state
      entity_id: binary_sensor.washer_b
      from: 'off'
      to: 'on'
    - platform: state
      entity_id: binary_sensor.washer_b
      from: 'on'
      to: 'off'
  condition:
    - condition: numeric_state
      entity_id: sensor.ha_uptime
      above: 5
  action:
    - service: notify.telegram
      data_template: 
        message: "{% if is_state('binary_sensor.washer_b','on') %}\U000023F3 Стирка начата!{% else %}\U0000231B Стирка завершена! Время стирки составило {{ ( (as_timestamp(strptime(states('sensor.date_time'),'%Y-%m-%d, %H:%M'))| round(0) - as_timestamp(states.timer.washer_b.last_changed)| int) / 60 )| round(0) }}мин.{% endif %}"
    - service: script.turn_on
      data_template: 
        entity_id: "{% if is_state('binary_sensor.washer_b','on') %}script.washer_timer_on{% else %}script.washer_timer_off{% endif %}"